"""made author_id in blogs not unique

Revision ID: 582cc894cec4
Revises: 9d148feb3746
Create Date: 2024-07-05 22:12:28.133361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582cc894cec4'
down_revision = '9d148feb3746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_index('author_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.create_index('author_id', ['author_id'], unique=True)

    # ### end Alembic commands ###
