"""deleted content column in blogs

Revision ID: a0da6788bffd
Revises: 582cc894cec4
Create Date: 2024-07-06 11:28:12.915758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0da6788bffd'
down_revision = '582cc894cec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
